# Generated by Django 4.1.3 on 2024-01-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgUpload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=4)),
                ('ID_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GEO_location', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgUpload.image', verbose_name='Passport_Image')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgUpload.person', verbose_name='Person')),
            ],
        ),
    ]
