# Generated by Django 4.1.3 on 2024-01-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUpload', '0002_person_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='expire',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
